Fatal error: exception Failure("local variable val already exists")